[package]
name = "slog-extlog-derive"
version = "5.0.0"
authors = ["Metaswitch Networks Ltd"]
license = "Apache-2.0"
description = "Custom derive code for slog-extlog"
homepage = "https://github.com/slog-rs/extlog"
repository = "https://github.com/slog-rs/extlog"
keywords = ["slog", "log", "logging"]
readme = "../README.md"

[dependencies]
slog =  { version = "2.1", features = ['nested-values'] }
syn = {version = "0.11.9", features = ["full"] }
quote = "0.3.10"
slog-extlog = { version = "5", path = ".." }
serde = "1.0"
serde_derive = "1.0"

[lib]
proc-macro = true

[dev-dependencies]
erased-serde = "0.3"
iobuffer = "0.1"
